apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: notizen-app
data:
  DATABASE_URL: "postgresql+psycopg://notizen:CHANGE-ME-IN-PRODUCTION@postgres:5432/notizen"
  LOG_LEVEL: "INFO"
