apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: notizen-app
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
  # NodePort for external access to dashboards
  type: NodePort
