apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: notizen-app
type: Opaque
stringData:
  POSTGRES_DB: notizen
  POSTGRES_USER: notizen
  # In production, change pw (obviously)
  POSTGRES_PASSWORD: CHANGE-ME-IN-PRODUCTION
